### ISSUE TITLE
Wie stellt man das mit der Email ein?

### ISSUE THREAD

**Issue by TomGamerTV** [noawinzp/smnbotskomplet#5]
Hallo,

Ich bekomme die Bestätigungs Email nicht. Wie stelle ich das ganze ein?

**Comment by TomGamerTV** [comment]
Und wie stellt man es ein. Das man Admin Rechte hat?

**Comment by netcodefox** [comment]
In smnbots/mail.php

**Comment by TomGamerTV** [comment]
Und wo vergebe ich die Rechte?

**Comment by TomGamerTV** [comment]
Und wie muss ich das in der mail.php eintragen? Ich bekomme bisher immer noch keine Email

**Comment by netcodefox** [comment]
Rechte in der db un das mit der mail.php ist echt nicht schwer  und mimmer noch es gipt kein support für ein panel was grottenschlecht geschrieben ist

**Comment by TomGamerTV** [comment]
Mir ist es bewusst das es in der Datenbank ist. Was muss man in der Datenbank eintragen. Und genauso wie beim mail.php. Ich habe das alles richtig eingetragen und es geht. Und wenn man es versucht es zu beschreiben. Bitte auch alles beschreiben!

**Comment by netcodefox** [comment]
Ich kann gerne um 16 oder 17 uhr via anydesk helfen kommen sie dafür nur auf ts.nxtbots.de

**Comment by TomGamerTV** [comment]
Kann erst morgen wieder um 15 Uhr

**Comment by netcodefox** [comment]
wenn du noch hilfe braust dann komm ts ts.nxtbots.de
