### ISSUE TITLE
Panel ohne ZIP Hochladen.

### ISSUE THREAD

**Issue by CookieCr2nk** [noawinzp/smnbotskomplet#6]
Wieso lädst du das Panel gezippt hoch, so kann man sich den Source Code nicht anschauen ohne es herunterzuladen. Github wurde ja extra deswegem entwickelt und ist keine Filesharing Plattform.

**Comment by netcodefox** [comment]
Kommen sie mal ts

**Comment by netcodefox** [comment]
Auf dein sie gerade eben waren
